# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
services:
  - postgresql
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start postgresql; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION; fi
  - psql -U postgres -tc 'SHOW server_version'
  - psql -U postgres -c '\conninfo'
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: linux
      env: POSTGRESQL_VERSION=9.4 PGHOST="/var/run/postgresql"
      julia: 0.6
    - os: linux
      env: POSTGRESQL_VERSION=9.6 PGHOST="/var/run/postgresql"
      julia: 0.6
    - os: linux
      env: POSTGRESQL_VERSION=9.4 PGHOST="/var/run/postgresql"
      julia: nightly
    - os: linux
      env: POSTGRESQL_VERSION=9.6 PGHOST="/var/run/postgresql"
      julia: nightly
    - os: osx
      julia: 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("LibPQ"); Pkg.test("LibPQ"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LibPQ")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter"); Pkg.add("DataFrames"); cd(Pkg.dir("LibPQ")); include(joinpath("docs", "make.jl"))'
