# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
services:
  - postgresql
addons:
  postgresql: "9.6"
julia:
  - 0.6
  - nightly
env:
  - POSTGRESQL_VERSION=9.4
  - POSTGRESQL_VERSION=9.6
before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
  - psql -U postgres -tc 'SHOW server_version'
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("LibPQ"); Pkg.test("LibPQ"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LibPQ")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("LibPQ")); include(joinpath("docs", "make.jl"))'
