environment:
  isSilent: "true"
  PGPORT: 5440
  matrix:
  - julia_version: 1.0
    pgc_postgresql_version: pg11
  - julia_version: 1.0
    pgc_postgresql_version: pg10
  - julia_version: 1.0
    pgc_postgresql_version: pg96
  - julia_version: 1.0
    pgc_postgresql_version: pg95
  - julia_version: 1.0
    pgc_postgresql_version: pg94
  - julia_version: nightly
    pgc_postgresql_version: pg11


platform:
  - x86 # 32-bit
  - x64 # 64-bit

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://s3.amazonaws.com/pgcentral/install.ps1'))"
  - bigsql\pgc install "%PGC_POSTGRESQL_VERSION%"
  - bigsql\pgc init "%PGC_POSTGRESQL_VERSION%" --port "%PGPORT%"
  - bigsql\%PGC_POSTGRESQL_VERSION%\%PGC_POSTGRESQL_VERSION%-env.bat
  - bigsql\pgc status
  - bigsql\pgc start "%PGC_POSTGRESQL_VERSION%"
  - psql -U postgres -tc 'SHOW server_version'
  - psql -U postgres -c '\conninfo'

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

# # Uncomment to support code coverage upload. Should only be enabled for packages
# # which would have coverage gaps without running on Windows
# on_success:
#   - echo "%JL_CODECOV_SCRIPT%"
#   - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
