version: 2

defaults: &DEFAULTS
  macos:
    xcode: "9.0"

test: &TEST
  steps:
    - checkout
    - run:
        name: Install Julia
        command: |
          curl -s -L --retry 7 -o julia.dmg \
            "https://julialang-s3.julialang.org/bin/mac/x64/$JULIA_VER/julia-$JULIA_VER-latest-mac64.dmg"
          mkdir jlmnt
          hdiutil mount -readonly -mountpoint jlmnt julia.dmg
          cp -a jlmnt/*.app/Contents/Resources/julia/* ~/
          if [ "$JULIA_VER" = "0.6" ]; then
            ~/bin/julia -e 'versioninfo()'
          else
            ~/bin/julia -e 'using InteractiveUtils; versioninfo()'
          fi
    - run:
        name: Install PostgreSQL
        command: |
          brew update || true
          brew install postgresql
    - run:
        name: Start PostgreSQL
        command: brew services start postgresql
    - run:
        name: Print PostgreSQL info
        command: |
          psql -d postgres -tc 'SHOW server_version'
          psql -d postgres -c '\conninfo'
    - run:
        name: Build package
        command: |
          # TODO: Update this for Pkg3 once we have a Project file
          ~/bin/julia -e "Pkg.clone(pwd(), \"$PKG_NAME\"); Pkg.build(\"$PKG_NAME\")"
    - run:
        name: Test package
        command: |
          if [ "$JULIA_VER" = "0.6" ]; then
            env LIBPQJL_DATABASE_USER=$USER ~/bin/julia -e "Pkg.test(\"$PKG_NAME\")"
          else
            env LIBPQJL_DATABASE_USER=$USER ~/bin/julia -e "using Pkg; Pkg.test(\"$PKG_NAME\")"
          fi

jobs:
  test_0.6:
    environment:
      PKG_NAME: LibPQ
      JULIA_VER: 0.6
    <<: [*DEFAULTS, *TEST]
  test_0.7:
    environment:
      PKG_NAME: LibPQ
      JULIA_VER: 0.7
    <<: [*DEFAULTS, *TEST]
  test_1.0:
    environment:
      PKG_NAME: LibPQ
      JULIA_VER: 1.0
    <<: [*DEFAULTS, *TEST]

workflows:
  version: 2
  test_macos:
    jobs:
      - test_0.6
      - test_0.7
      - test_1.0
