version: 2

defaults: &DEFAULTS
  environment:
    PKG_NAME: DeferredFutures
  macos:
    xcode: "9.0"

v0.6: &POINT_SIX
  docker:
    - image: julia:0.6

test: &TEST
  steps:
    - checkout
    - run:
        name: Install PostgreSQL
        command: brew install postgresql
    - run:
        name: Start PostgreSQL
        command: brew services start postgresql
    - run:
        name: Print PostgreSQL info
        command: |
          psql -U postgres -tc 'SHOW server_version'
          psql -U postgres -c '\conninfo'
    - run:
        name: Build package
        command: julia -e "Pkg.clone(pwd()); Pkg.build(\"$PKG_NAME\")"
    - run:
        name: Test package
        command: julia -e "Pkg.test(\"$PKG_NAME\")"

jobs:
  test_0.6:
    <<: [*DEFAULTS, *POINT_SIX, *TEST]

workflows:
  version: 2
  test_macos:
    jobs:
      - test_0.6
